name: Autograding

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'temurin' 

    - name: Compile tests
      run: javac -cp lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar:lib/rars.jar -d bin src/test/java/TaTest.java

    - name: Run tests
      run: java -cp bin:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar:lib/rars.jar org.junit.runner.JUnitCore TaTest
